/* Generated by re2c */
#line 1 "src/lexer.re"
// vim:set ft=cpp:

#include "adlib/lib.h"
#include "adlib/set.h"
// "fixstr.h" must be included before "map.h"
#include "fixstr.h"
#include "adlib/map.h"

#include "lexer.h"

const char *SymbolNames[] = {
  "SymNone",
  "SymAuto",
  "SymBreak",
  "SymCase",
  "SymChar",
  "SymConst",
  "SymContinue",
  "SymDefault",
  "SymDo",
  "SymDouble",
  "SymElse",
  "SymEnum",
  "SymExtern",
  "SymFloat",
  "SymFor",
  "SymGoto",
  "SymIf",
  "SymInline",
  "SymInt",
  "SymLong",
  "SymRegister",
  "SymReturn",
  "SymShort",
  "SymSigned",
  "SymSizeof",
  "SymStatic",
  "SymStruct",
  "SymSwitch",
  "SymTypedef",
  "SymUnion",
  "SymUnsigned",
  "SymVoid",
  "SymVolatile",
  "SymWhile",
  "SymIdent",
  "SymLiteral",
  "SymOp",
  "SymSemicolon",
  "SymLPar",
  "SymRPar",
  "SymLBrkt",
  "SymRBrkt",
  "SymLBrace",
  "SymRBrace",
  "SymWS",
  "SymEOL",
  "SymComment",
  "SymBAD",
  "SymPPIf",
  "SymPPElse",
  "SymPPElif",
  "SymPPEndif",
  "SymPPDef",
  "SymPPOther",
  "SymEOF",
};

typedef Map<FixStr, Str *> InternMap;

Str *Intern(const char *ptr, Int len) {
  static InternMap *map = NULL;
  if (!map) {
    GCVar(map, new InternMap());
  }
  FixStr fs;
  fs.str = ptr;
  fs.len = len;
  Str *result = map->get(fs, NULL);
  if (!result) {
    result = new Str(ptr, len);
    // `ptr` above is an interior pointer whose contents may disappear
    // due to GC once the `SourceFile` object containing it is no
    // longer reachable.
    //
    // Therefore, we replace it with `result->c_str()`. This is not only
    // not an interior pointer, but is kept alive by the value that the
    // key is in use for.
    fs.str = result->c_str();
    map->add(fs, result);
  }
  return result;
}

#define PUSH_TOKEN(s) \
  token.sym = s; \
  goto pushtoken;

bool ReadSource(SourceFile *source) {
  if (!source->filedata) {
    source->filedata = ReadFile(source->filename);
  }
  return source->filedata != NULL;
}

bool Tokenize(SourceFile *source) {
  Str *input = source->filedata;
  const char *cursor = input->c_str();
  const char *marker = NULL;
  const char *ctxmarker = NULL;
  bool done = false;
  bool error = false;
  TokenList *result = new TokenList();
  Token token;
  while (!done) {
    const char *last = cursor;
    
#line 121 "src/lexer.cc"
{
	unsigned char yych;
	unsigned int yyaccept = 0;
	yych = *cursor;
	switch (yych) {
	case 0x00:	goto yy2;
	case '\t':
	case '\f':
	case ' ':	goto yy6;
	case '\n':	goto yy9;
	case '\r':	goto yy11;
	case '!':
	case '%':
	case '*':
	case '=':
	case '^':	goto yy12;
	case '"':	goto yy14;
	case '#':	goto yy15;
	case '&':	goto yy17;
	case '\'':	goto yy18;
	case '(':	goto yy19;
	case ')':	goto yy21;
	case '+':	goto yy23;
	case ',':
	case ':':
	case '?':
	case '~':	goto yy24;
	case '-':	goto yy25;
	case '.':	goto yy26;
	case '/':	goto yy27;
	case '0':	goto yy28;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy30;
	case ';':	goto yy32;
	case '<':	goto yy34;
	case '>':	goto yy35;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'h':
	case 'j':
	case 'k':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	case 'L':	goto yy39;
	case '[':	goto yy40;
	case '\\':	goto yy42;
	case ']':	goto yy43;
	case 'a':	goto yy45;
	case 'b':	goto yy46;
	case 'c':	goto yy47;
	case 'd':	goto yy48;
	case 'e':	goto yy49;
	case 'f':	goto yy50;
	case 'g':	goto yy51;
	case 'i':	goto yy52;
	case 'l':	goto yy53;
	case 'r':	goto yy54;
	case 's':	goto yy55;
	case 't':	goto yy56;
	case 'u':	goto yy57;
	case 'v':	goto yy58;
	case 'w':	goto yy59;
	case '{':	goto yy60;
	case '|':	goto yy62;
	case '}':	goto yy63;
	default:	goto yy4;
	}
yy2:
	++cursor;
#line 211 "src/lexer.re"
	{ done = true; continue; }
#line 230 "src/lexer.cc"
yy4:
	++cursor;
yy5:
#line 212 "src/lexer.re"
	{ error = true; PUSH_TOKEN(SymBAD); }
#line 236 "src/lexer.cc"
yy6:
	yych = *++cursor;
	switch (yych) {
	case '\t':
	case '\f':
	case ' ':	goto yy6;
	default:	goto yy8;
	}
yy8:
#line 201 "src/lexer.re"
	{ PUSH_TOKEN(SymWS); }
#line 248 "src/lexer.cc"
yy9:
	++cursor;
yy10:
#line 199 "src/lexer.re"
	{ PUSH_TOKEN(SymEOL); }
#line 254 "src/lexer.cc"
yy11:
	yych = *++cursor;
	switch (yych) {
	case '\n':	goto yy9;
	default:	goto yy10;
	}
yy12:
	yych = *++cursor;
	switch (yych) {
	case '=':	goto yy65;
	default:	goto yy13;
	}
yy13:
#line 194 "src/lexer.re"
	{ PUSH_TOKEN(SymOp); }
#line 270 "src/lexer.cc"
yy14:
	yyaccept = 0;
	yych = *(marker = ++cursor);
	switch (yych) {
	case 0x00:
	case '\n':
	case '\r':	goto yy5;
	default:	goto yy68;
	}
yy15:
	yych = *++cursor;
	switch (yych) {
	case 0x00:
	case '\n':
	case '\r':	goto yy73;
	case '\t':
	case '\f':
	case ' ':	goto yy15;
	case 'd':	goto yy77;
	case 'e':	goto yy78;
	case 'i':	goto yy79;
	case 'u':	goto yy80;
	default:	goto yy75;
	}
yy17:
	yych = *++cursor;
	switch (yych) {
	case '&':
	case '=':	goto yy65;
	default:	goto yy13;
	}
yy18:
	yyaccept = 0;
	yych = *(marker = ++cursor);
	switch (yych) {
	case 0x00:
	case '\n':
	case '\r':
	case '\'':	goto yy5;
	case '\\':	goto yy82;
	default:	goto yy81;
	}
yy19:
	++cursor;
#line 188 "src/lexer.re"
	{ PUSH_TOKEN(SymLPar); }
#line 317 "src/lexer.cc"
yy21:
	++cursor;
#line 189 "src/lexer.re"
	{ PUSH_TOKEN(SymRPar); }
#line 322 "src/lexer.cc"
yy23:
	yych = *++cursor;
	switch (yych) {
	case '+':
	case '=':	goto yy65;
	default:	goto yy13;
	}
yy24:
	++cursor;
	goto yy13;
yy25:
	yych = *++cursor;
	switch (yych) {
	case '-':
	case '=':
	case '>':	goto yy65;
	default:	goto yy13;
	}
yy26:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
	case '.':	goto yy83;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy84;
	default:	goto yy13;
	}
yy27:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
	case '*':	goto yy87;
	case '/':	goto yy89;
	case '=':	goto yy65;
	default:	goto yy13;
	}
yy28:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'E':
	case 'e':	goto yy93;
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy96;
	case 'X':
	case 'x':	goto yy98;
	default:	goto yy29;
	}
yy29:
#line 182 "src/lexer.re"
	{ PUSH_TOKEN(SymLiteral); }
#line 395 "src/lexer.cc"
yy30:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
	case '.':	goto yy90;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy30;
	case 'E':
	case 'e':	goto yy95;
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy96;
	default:	goto yy29;
	}
yy32:
	++cursor;
#line 196 "src/lexer.re"
	{ PUSH_TOKEN(SymSemicolon); }
#line 423 "src/lexer.cc"
yy34:
	yych = *++cursor;
	switch (yych) {
	case '<':	goto yy99;
	case '=':	goto yy65;
	default:	goto yy13;
	}
yy35:
	yych = *++cursor;
	switch (yych) {
	case '=':	goto yy65;
	case '>':	goto yy99;
	default:	goto yy13;
	}
yy36:
	yych = *++cursor;
yy37:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy38;
	}
yy38:
#line 179 "src/lexer.re"
	{ PUSH_TOKEN(SymIdent); }
#line 510 "src/lexer.cc"
yy39:
	yyaccept = 3;
	yych = *(marker = ++cursor);
	switch (yych) {
	case '"':	goto yy67;
	case '\'':	goto yy100;
	default:	goto yy37;
	}
yy40:
	++cursor;
#line 190 "src/lexer.re"
	{ PUSH_TOKEN(SymLBrkt); }
#line 523 "src/lexer.cc"
yy42:
	yyaccept = 0;
	yych = *(marker = ++cursor);
	switch (yych) {
	case '\t':
	case '\n':
	case '\f':
	case '\r':
	case ' ':	goto yy102;
	default:	goto yy5;
	}
yy43:
	++cursor;
#line 191 "src/lexer.re"
	{ PUSH_TOKEN(SymRBrkt); }
#line 539 "src/lexer.cc"
yy45:
	yych = *++cursor;
	switch (yych) {
	case 'u':	goto yy106;
	default:	goto yy37;
	}
yy46:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy107;
	default:	goto yy37;
	}
yy47:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy108;
	case 'h':	goto yy109;
	case 'o':	goto yy110;
	default:	goto yy37;
	}
yy48:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy111;
	case 'o':	goto yy112;
	default:	goto yy37;
	}
yy49:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy114;
	case 'n':	goto yy115;
	case 'x':	goto yy116;
	default:	goto yy37;
	}
yy50:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy117;
	case 'o':	goto yy118;
	default:	goto yy37;
	}
yy51:
	yych = *++cursor;
	switch (yych) {
	case 'o':	goto yy119;
	default:	goto yy37;
	}
yy52:
	yych = *++cursor;
	switch (yych) {
	case 'f':	goto yy120;
	case 'n':	goto yy122;
	default:	goto yy37;
	}
yy53:
	yych = *++cursor;
	switch (yych) {
	case 'o':	goto yy123;
	default:	goto yy37;
	}
yy54:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy124;
	default:	goto yy37;
	}
yy55:
	yych = *++cursor;
	switch (yych) {
	case 'h':	goto yy125;
	case 'i':	goto yy126;
	case 't':	goto yy127;
	case 'w':	goto yy128;
	default:	goto yy37;
	}
yy56:
	yych = *++cursor;
	switch (yych) {
	case 'y':	goto yy129;
	default:	goto yy37;
	}
yy57:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy130;
	default:	goto yy37;
	}
yy58:
	yych = *++cursor;
	switch (yych) {
	case 'o':	goto yy131;
	default:	goto yy37;
	}
yy59:
	yych = *++cursor;
	switch (yych) {
	case 'h':	goto yy132;
	default:	goto yy37;
	}
yy60:
	++cursor;
#line 192 "src/lexer.re"
	{ PUSH_TOKEN(SymLBrace); }
#line 644 "src/lexer.cc"
yy62:
	yych = *++cursor;
	switch (yych) {
	case '=':
	case '|':	goto yy65;
	default:	goto yy13;
	}
yy63:
	++cursor;
#line 193 "src/lexer.re"
	{ PUSH_TOKEN(SymRBrace); }
#line 656 "src/lexer.cc"
yy65:
	++cursor;
yy66:
#line 195 "src/lexer.re"
	{ PUSH_TOKEN(SymOp); }
#line 662 "src/lexer.cc"
yy67:
	yych = *++cursor;
yy68:
	switch (yych) {
	case 0x00:
	case '\n':
	case '\r':	goto yy69;
	case '"':	goto yy70;
	case '\\':	goto yy72;
	default:	goto yy67;
	}
yy69:
	cursor = marker;
	switch (yyaccept) {
	case 0: 	goto yy5;
	case 1: 	goto yy13;
	case 2: 	goto yy29;
	case 3: 	goto yy38;
	case 4: 	goto yy86;
	case 5: 	goto yy91;
	default:	goto yy94;
	}
yy70:
	++cursor;
#line 184 "src/lexer.re"
	{ PUSH_TOKEN(SymLiteral); }
#line 689 "src/lexer.cc"
yy72:
	yych = *++cursor;
	switch (yych) {
	case 0x00:
	case '\n':
	case '\r':	goto yy69;
	default:	goto yy67;
	}
yy73:
	++cursor;
	cursor -= 1;
#line 210 "src/lexer.re"
	{ PUSH_TOKEN(SymPPOther); }
#line 703 "src/lexer.cc"
yy75:
	yych = *++cursor;
yy76:
	switch (yych) {
	case 0x00:
	case '\n':
	case '\r':	goto yy73;
	default:	goto yy75;
	}
yy77:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy133;
	default:	goto yy76;
	}
yy78:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy134;
	case 'n':	goto yy135;
	default:	goto yy76;
	}
yy79:
	yych = *++cursor;
	switch (yych) {
	case 'f':	goto yy136;
	default:	goto yy76;
	}
yy80:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy137;
	default:	goto yy76;
	}
yy81:
	yych = *++cursor;
	switch (yych) {
	case '\'':	goto yy138;
	default:	goto yy69;
	}
yy82:
	yych = *++cursor;
	switch (yych) {
	case '\'':
	case '\\':	goto yy140;
	default:	goto yy141;
	}
yy83:
	yych = *++cursor;
	switch (yych) {
	case '.':	goto yy65;
	default:	goto yy69;
	}
yy84:
	yyaccept = 4;
	yych = *(marker = ++cursor);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy84;
	case 'E':
	case 'e':	goto yy142;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy143;
	default:	goto yy86;
	}
yy86:
#line 186 "src/lexer.re"
	{ PUSH_TOKEN(SymLiteral); }
#line 782 "src/lexer.cc"
yy87:
	++cursor;
#line 198 "src/lexer.re"
	{ goto comment; }
#line 787 "src/lexer.cc"
yy89:
	yych = *++cursor;
	switch (yych) {
	case 0x00:
	case '\n':
	case '\r':	goto yy69;
	default:	goto yy144;
	}
yy90:
	yyaccept = 5;
	yych = *(marker = ++cursor);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy84;
	case 'E':
	case 'e':	goto yy147;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy148;
	default:	goto yy91;
	}
yy91:
#line 187 "src/lexer.re"
	{ PUSH_TOKEN(SymLiteral); }
#line 821 "src/lexer.cc"
yy92:
	yyaccept = 6;
	yych = *(marker = ++cursor);
yy93:
	switch (yych) {
	case '.':	goto yy90;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy92;
	case '8':
	case '9':	goto yy30;
	case 'E':
	case 'e':	goto yy95;
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy149;
	default:	goto yy94;
	}
yy94:
#line 181 "src/lexer.re"
	{ PUSH_TOKEN(SymLiteral); }
#line 849 "src/lexer.cc"
yy95:
	yych = *++cursor;
	switch (yych) {
	case '+':
	case '-':	goto yy151;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy152;
	default:	goto yy69;
	}
yy96:
	yych = *++cursor;
	switch (yych) {
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy96;
	default:	goto yy29;
	}
yy98:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy155;
	default:	goto yy69;
	}
yy99:
	yych = *++cursor;
	switch (yych) {
	case '=':	goto yy65;
	default:	goto yy66;
	}
yy100:
	yych = *++cursor;
	switch (yych) {
	case 0x00:
	case '\n':
	case '\r':
	case '\'':	goto yy69;
	case '\\':	goto yy82;
	default:	goto yy81;
	}
yy101:
	yych = *++cursor;
yy102:
	switch (yych) {
	case '\t':
	case '\f':
	case ' ':	goto yy101;
	case '\n':
		ctxmarker = cursor;
		goto yy103;
	case '\r':
		ctxmarker = cursor;
		goto yy105;
	default:	goto yy69;
	}
yy103:
	++cursor;
yy104:
	cursor = ctxmarker;
#line 200 "src/lexer.re"
	{ PUSH_TOKEN(SymWS); }
#line 940 "src/lexer.cc"
yy105:
	yych = *++cursor;
	switch (yych) {
	case '\n':	goto yy103;
	default:	goto yy104;
	}
yy106:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy158;
	default:	goto yy37;
	}
yy107:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy159;
	default:	goto yy37;
	}
yy108:
	yych = *++cursor;
	switch (yych) {
	case 's':	goto yy160;
	default:	goto yy37;
	}
yy109:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy161;
	default:	goto yy37;
	}
yy110:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy162;
	default:	goto yy37;
	}
yy111:
	yych = *++cursor;
	switch (yych) {
	case 'f':	goto yy163;
	default:	goto yy37;
	}
yy112:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	case 'u':	goto yy164;
	default:	goto yy113;
	}
yy113:
#line 153 "src/lexer.re"
	{ PUSH_TOKEN(SymDo); }
#line 1054 "src/lexer.cc"
yy114:
	yych = *++cursor;
	switch (yych) {
	case 's':	goto yy165;
	default:	goto yy37;
	}
yy115:
	yych = *++cursor;
	switch (yych) {
	case 'u':	goto yy166;
	default:	goto yy37;
	}
yy116:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy167;
	default:	goto yy37;
	}
yy117:
	yych = *++cursor;
	switch (yych) {
	case 'o':	goto yy168;
	default:	goto yy37;
	}
yy118:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy169;
	default:	goto yy37;
	}
yy119:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy171;
	default:	goto yy37;
	}
yy120:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy121;
	}
yy121:
#line 161 "src/lexer.re"
	{ PUSH_TOKEN(SymIf); }
#line 1162 "src/lexer.cc"
yy122:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy172;
	case 't':	goto yy173;
	default:	goto yy37;
	}
yy123:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy175;
	default:	goto yy37;
	}
yy124:
	yych = *++cursor;
	switch (yych) {
	case 'g':	goto yy176;
	case 't':	goto yy177;
	default:	goto yy37;
	}
yy125:
	yych = *++cursor;
	switch (yych) {
	case 'o':	goto yy178;
	default:	goto yy37;
	}
yy126:
	yych = *++cursor;
	switch (yych) {
	case 'g':	goto yy179;
	case 'z':	goto yy180;
	default:	goto yy37;
	}
yy127:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy181;
	case 'r':	goto yy182;
	default:	goto yy37;
	}
yy128:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy183;
	default:	goto yy37;
	}
yy129:
	yych = *++cursor;
	switch (yych) {
	case 'p':	goto yy184;
	default:	goto yy37;
	}
yy130:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy185;
	case 's':	goto yy186;
	default:	goto yy37;
	}
yy131:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy187;
	case 'l':	goto yy188;
	default:	goto yy37;
	}
yy132:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy189;
	default:	goto yy37;
	}
yy133:
	yych = *++cursor;
	switch (yych) {
	case 'f':	goto yy190;
	default:	goto yy76;
	}
yy134:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy191;
	case 's':	goto yy192;
	default:	goto yy76;
	}
yy135:
	yych = *++cursor;
	switch (yych) {
	case 'd':	goto yy193;
	default:	goto yy76;
	}
yy136:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy75;
	case 'd':	goto yy198;
	case 'n':	goto yy199;
	default:	goto yy197;
	}
yy137:
	yych = *++cursor;
	switch (yych) {
	case 'd':	goto yy200;
	default:	goto yy76;
	}
yy138:
	++cursor;
#line 183 "src/lexer.re"
	{ PUSH_TOKEN(SymLiteral); }
#line 1332 "src/lexer.cc"
yy140:
	yych = *++cursor;
yy141:
	switch (yych) {
	case 0x00:
	case '\n':
	case '\r':
	case '\\':	goto yy69;
	case '\'':	goto yy138;
	default:	goto yy140;
	}
yy142:
	yych = *++cursor;
	switch (yych) {
	case '+':
	case '-':	goto yy201;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy202;
	default:	goto yy69;
	}
yy143:
	++cursor;
	goto yy86;
yy144:
	yych = *++cursor;
	switch (yych) {
	case 0x00:
	case '\n':
	case '\r':	goto yy146;
	default:	goto yy144;
	}
yy146:
#line 197 "src/lexer.re"
	{ PUSH_TOKEN(SymComment); }
#line 1375 "src/lexer.cc"
yy147:
	yych = *++cursor;
	switch (yych) {
	case '+':
	case '-':	goto yy204;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy205;
	default:	goto yy69;
	}
yy148:
	++cursor;
	goto yy91;
yy149:
	yych = *++cursor;
	switch (yych) {
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy149;
	default:	goto yy94;
	}
yy151:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy152;
	default:	goto yy69;
	}
yy152:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy152;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy207;
	default:	goto yy154;
	}
yy154:
#line 185 "src/lexer.re"
	{ PUSH_TOKEN(SymLiteral); }
#line 1442 "src/lexer.cc"
yy155:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy155;
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy208;
	default:	goto yy157;
	}
yy157:
#line 180 "src/lexer.re"
	{ PUSH_TOKEN(SymLiteral); }
#line 1477 "src/lexer.cc"
yy158:
	yych = *++cursor;
	switch (yych) {
	case 'o':	goto yy210;
	default:	goto yy37;
	}
yy159:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy212;
	default:	goto yy37;
	}
yy160:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy213;
	default:	goto yy37;
	}
yy161:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy215;
	default:	goto yy37;
	}
yy162:
	yych = *++cursor;
	switch (yych) {
	case 's':	goto yy217;
	case 't':	goto yy218;
	default:	goto yy37;
	}
yy163:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy219;
	default:	goto yy37;
	}
yy164:
	yych = *++cursor;
	switch (yych) {
	case 'b':	goto yy220;
	default:	goto yy37;
	}
yy165:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy221;
	default:	goto yy37;
	}
yy166:
	yych = *++cursor;
	switch (yych) {
	case 'm':	goto yy223;
	default:	goto yy37;
	}
yy167:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy225;
	default:	goto yy37;
	}
yy168:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy226;
	default:	goto yy37;
	}
yy169:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy170;
	}
yy170:
#line 159 "src/lexer.re"
	{ PUSH_TOKEN(SymFor); }
#line 1616 "src/lexer.cc"
yy171:
	yych = *++cursor;
	switch (yych) {
	case 'o':	goto yy227;
	default:	goto yy37;
	}
yy172:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy229;
	default:	goto yy37;
	}
yy173:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy174;
	}
yy174:
#line 163 "src/lexer.re"
	{ PUSH_TOKEN(SymInt); }
#line 1700 "src/lexer.cc"
yy175:
	yych = *++cursor;
	switch (yych) {
	case 'g':	goto yy230;
	default:	goto yy37;
	}
yy176:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy232;
	default:	goto yy37;
	}
yy177:
	yych = *++cursor;
	switch (yych) {
	case 'u':	goto yy233;
	default:	goto yy37;
	}
yy178:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy234;
	default:	goto yy37;
	}
yy179:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy235;
	default:	goto yy37;
	}
yy180:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy236;
	default:	goto yy37;
	}
yy181:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy237;
	default:	goto yy37;
	}
yy182:
	yych = *++cursor;
	switch (yych) {
	case 'u':	goto yy238;
	default:	goto yy37;
	}
yy183:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy239;
	default:	goto yy37;
	}
yy184:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy240;
	default:	goto yy37;
	}
yy185:
	yych = *++cursor;
	switch (yych) {
	case 'o':	goto yy241;
	default:	goto yy37;
	}
yy186:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy242;
	default:	goto yy37;
	}
yy187:
	yych = *++cursor;
	switch (yych) {
	case 'd':	goto yy243;
	default:	goto yy37;
	}
yy188:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy245;
	default:	goto yy37;
	}
yy189:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy246;
	default:	goto yy37;
	}
yy190:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy247;
	default:	goto yy76;
	}
yy191:
	yych = *++cursor;
	switch (yych) {
	case 'f':	goto yy248;
	default:	goto yy76;
	}
yy192:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy249;
	default:	goto yy76;
	}
yy193:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy250;
	default:	goto yy76;
	}
yy194:
	++cursor;
	cursor -= 1;
#line 202 "src/lexer.re"
	{ PUSH_TOKEN(SymPPIf); }
#line 1820 "src/lexer.cc"
yy196:
	yych = *++cursor;
yy197:
	switch (yych) {
	case 0x00:
	case '\n':
	case '\r':	goto yy194;
	default:	goto yy196;
	}
yy198:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy251;
	default:	goto yy76;
	}
yy199:
	yych = *++cursor;
	switch (yych) {
	case 'd':	goto yy252;
	default:	goto yy76;
	}
yy200:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy253;
	default:	goto yy76;
	}
yy201:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy202;
	default:	goto yy69;
	}
yy202:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy202;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy143;
	default:	goto yy86;
	}
yy204:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy205;
	default:	goto yy69;
	}
yy205:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy205;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy148;
	default:	goto yy91;
	}
yy207:
	++cursor;
	goto yy154;
yy208:
	yych = *++cursor;
	switch (yych) {
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy208;
	default:	goto yy157;
	}
yy210:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy211;
	}
yy211:
#line 146 "src/lexer.re"
	{ PUSH_TOKEN(SymAuto); }
#line 1999 "src/lexer.cc"
yy212:
	yych = *++cursor;
	switch (yych) {
	case 'k':	goto yy254;
	default:	goto yy37;
	}
yy213:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy214;
	}
yy214:
#line 148 "src/lexer.re"
	{ PUSH_TOKEN(SymCase); }
#line 2077 "src/lexer.cc"
yy215:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy216;
	}
yy216:
#line 149 "src/lexer.re"
	{ PUSH_TOKEN(SymChar); }
#line 2149 "src/lexer.cc"
yy217:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy256;
	default:	goto yy37;
	}
yy218:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy258;
	default:	goto yy37;
	}
yy219:
	yych = *++cursor;
	switch (yych) {
	case 'u':	goto yy259;
	default:	goto yy37;
	}
yy220:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy260;
	default:	goto yy37;
	}
yy221:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy222;
	}
yy222:
#line 155 "src/lexer.re"
	{ PUSH_TOKEN(SymElse); }
#line 2245 "src/lexer.cc"
yy223:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy224;
	}
yy224:
#line 156 "src/lexer.re"
	{ PUSH_TOKEN(SymEnum); }
#line 2317 "src/lexer.cc"
yy225:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy261;
	default:	goto yy37;
	}
yy226:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy262;
	default:	goto yy37;
	}
yy227:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy228;
	}
yy228:
#line 160 "src/lexer.re"
	{ PUSH_TOKEN(SymGoto); }
#line 2401 "src/lexer.cc"
yy229:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy264;
	default:	goto yy37;
	}
yy230:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy231;
	}
yy231:
#line 164 "src/lexer.re"
	{ PUSH_TOKEN(SymLong); }
#line 2479 "src/lexer.cc"
yy232:
	yych = *++cursor;
	switch (yych) {
	case 's':	goto yy265;
	default:	goto yy37;
	}
yy233:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy266;
	default:	goto yy37;
	}
yy234:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy267;
	default:	goto yy37;
	}
yy235:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy269;
	default:	goto yy37;
	}
yy236:
	yych = *++cursor;
	switch (yych) {
	case 'o':	goto yy270;
	default:	goto yy37;
	}
yy237:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy271;
	default:	goto yy37;
	}
yy238:
	yych = *++cursor;
	switch (yych) {
	case 'c':	goto yy272;
	default:	goto yy37;
	}
yy239:
	yych = *++cursor;
	switch (yych) {
	case 'c':	goto yy273;
	default:	goto yy37;
	}
yy240:
	yych = *++cursor;
	switch (yych) {
	case 'd':	goto yy274;
	default:	goto yy37;
	}
yy241:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy275;
	default:	goto yy37;
	}
yy242:
	yych = *++cursor;
	switch (yych) {
	case 'g':	goto yy277;
	default:	goto yy37;
	}
yy243:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy244;
	}
yy244:
#line 176 "src/lexer.re"
	{ PUSH_TOKEN(SymVoid); }
#line 2617 "src/lexer.cc"
yy245:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy278;
	default:	goto yy37;
	}
yy246:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy279;
	default:	goto yy37;
	}
yy247:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy281;
	default:	goto yy76;
	}
yy248:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy75;
	default:	goto yy285;
	}
yy249:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy75;
	default:	goto yy289;
	}
yy250:
	yych = *++cursor;
	switch (yych) {
	case 'f':	goto yy290;
	default:	goto yy76;
	}
yy251:
	yych = *++cursor;
	switch (yych) {
	case 'f':	goto yy291;
	default:	goto yy76;
	}
yy252:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy292;
	default:	goto yy76;
	}
yy253:
	yych = *++cursor;
	switch (yych) {
	case 'f':	goto yy293;
	default:	goto yy76;
	}
yy254:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy255;
	}
yy255:
#line 147 "src/lexer.re"
	{ PUSH_TOKEN(SymBreak); }
#line 2867 "src/lexer.cc"
yy256:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy257;
	}
yy257:
#line 150 "src/lexer.re"
	{ PUSH_TOKEN(SymConst); }
#line 2939 "src/lexer.cc"
yy258:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy294;
	default:	goto yy37;
	}
yy259:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy295;
	default:	goto yy37;
	}
yy260:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy296;
	default:	goto yy37;
	}
yy261:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy298;
	default:	goto yy37;
	}
yy262:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy263;
	}
yy263:
#line 158 "src/lexer.re"
	{ PUSH_TOKEN(SymFloat); }
#line 3035 "src/lexer.cc"
yy264:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy300;
	default:	goto yy37;
	}
yy265:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy302;
	default:	goto yy37;
	}
yy266:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy303;
	default:	goto yy37;
	}
yy267:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy268;
	}
yy268:
#line 167 "src/lexer.re"
	{ PUSH_TOKEN(SymShort); }
#line 3125 "src/lexer.cc"
yy269:
	yych = *++cursor;
	switch (yych) {
	case 'd':	goto yy305;
	default:	goto yy37;
	}
yy270:
	yych = *++cursor;
	switch (yych) {
	case 'f':	goto yy307;
	default:	goto yy37;
	}
yy271:
	yych = *++cursor;
	switch (yych) {
	case 'c':	goto yy309;
	default:	goto yy37;
	}
yy272:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy311;
	default:	goto yy37;
	}
yy273:
	yych = *++cursor;
	switch (yych) {
	case 'h':	goto yy313;
	default:	goto yy37;
	}
yy274:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy315;
	default:	goto yy37;
	}
yy275:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy276;
	}
yy276:
#line 174 "src/lexer.re"
	{ PUSH_TOKEN(SymUnion); }
#line 3233 "src/lexer.cc"
yy277:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy316;
	default:	goto yy37;
	}
yy278:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy317;
	default:	goto yy37;
	}
yy279:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy280;
	}
yy280:
#line 178 "src/lexer.re"
	{ PUSH_TOKEN(SymWhile); }
#line 3317 "src/lexer.cc"
yy281:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy318;
	default:	goto yy76;
	}
yy282:
	++cursor;
	cursor -= 1;
#line 206 "src/lexer.re"
	{ PUSH_TOKEN(SymPPElif); }
#line 3329 "src/lexer.cc"
yy284:
	yych = *++cursor;
yy285:
	switch (yych) {
	case 0x00:
	case '\n':
	case '\r':	goto yy282;
	default:	goto yy284;
	}
yy286:
	++cursor;
	cursor -= 1;
#line 205 "src/lexer.re"
	{ PUSH_TOKEN(SymPPElse); }
#line 3344 "src/lexer.cc"
yy288:
	yych = *++cursor;
yy289:
	switch (yych) {
	case 0x00:
	case '\n':
	case '\r':	goto yy286;
	default:	goto yy288;
	}
yy290:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy75;
	default:	goto yy322;
	}
yy291:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy75;
	default:	goto yy326;
	}
yy292:
	yych = *++cursor;
	switch (yych) {
	case 'f':	goto yy327;
	default:	goto yy76;
	}
yy293:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy328;
	default:	goto yy76;
	}
yy294:
	yych = *++cursor;
	switch (yych) {
	case 'u':	goto yy329;
	default:	goto yy37;
	}
yy295:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy330;
	default:	goto yy37;
	}
yy296:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy297;
	}
yy297:
#line 154 "src/lexer.re"
	{ PUSH_TOKEN(SymDouble); }
#line 3585 "src/lexer.cc"
yy298:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy299;
	}
yy299:
#line 157 "src/lexer.re"
	{ PUSH_TOKEN(SymExtern); }
#line 3657 "src/lexer.cc"
yy300:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy301;
	}
yy301:
#line 162 "src/lexer.re"
	{ PUSH_TOKEN(SymInline); }
#line 3729 "src/lexer.cc"
yy302:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy332;
	default:	goto yy37;
	}
yy303:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy304;
	}
yy304:
#line 166 "src/lexer.re"
	{ PUSH_TOKEN(SymReturn); }
#line 3807 "src/lexer.cc"
yy305:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy306;
	}
yy306:
#line 168 "src/lexer.re"
	{ PUSH_TOKEN(SymSigned); }
#line 3879 "src/lexer.cc"
yy307:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy308;
	}
yy308:
#line 169 "src/lexer.re"
	{ PUSH_TOKEN(SymSizeof); }
#line 3951 "src/lexer.cc"
yy309:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy310;
	}
yy310:
#line 170 "src/lexer.re"
	{ PUSH_TOKEN(SymStatic); }
#line 4023 "src/lexer.cc"
yy311:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy312;
	}
yy312:
#line 171 "src/lexer.re"
	{ PUSH_TOKEN(SymStruct); }
#line 4095 "src/lexer.cc"
yy313:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy314;
	}
yy314:
#line 172 "src/lexer.re"
	{ PUSH_TOKEN(SymSwitch); }
#line 4167 "src/lexer.cc"
yy315:
	yych = *++cursor;
	switch (yych) {
	case 'f':	goto yy333;
	default:	goto yy37;
	}
yy316:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy335;
	default:	goto yy37;
	}
yy317:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy336;
	default:	goto yy37;
	}
yy318:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy75;
	default:	goto yy340;
	}
yy319:
	++cursor;
	cursor -= 1;
#line 207 "src/lexer.re"
	{ PUSH_TOKEN(SymPPEndif); }
#line 4259 "src/lexer.cc"
yy321:
	yych = *++cursor;
yy322:
	switch (yych) {
	case 0x00:
	case '\n':
	case '\r':	goto yy319;
	default:	goto yy321;
	}
yy323:
	++cursor;
	cursor -= 1;
#line 203 "src/lexer.re"
	{ PUSH_TOKEN(SymPPIf); }
#line 4274 "src/lexer.cc"
yy325:
	yych = *++cursor;
yy326:
	switch (yych) {
	case 0x00:
	case '\n':
	case '\r':	goto yy323;
	default:	goto yy325;
	}
yy327:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy75;
	default:	goto yy344;
	}
yy328:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy345;
	default:	goto yy76;
	}
yy329:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy346;
	default:	goto yy37;
	}
yy330:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy331;
	}
yy331:
#line 152 "src/lexer.re"
	{ PUSH_TOKEN(SymDefault); }
#line 4435 "src/lexer.cc"
yy332:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy348;
	default:	goto yy37;
	}
yy333:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy334;
	}
yy334:
#line 173 "src/lexer.re"
	{ PUSH_TOKEN(SymTypedef); }
#line 4513 "src/lexer.cc"
yy335:
	yych = *++cursor;
	switch (yych) {
	case 'd':	goto yy350;
	default:	goto yy37;
	}
yy336:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy352;
	default:	goto yy37;
	}
yy337:
	++cursor;
	cursor -= 1;
#line 208 "src/lexer.re"
	{ PUSH_TOKEN(SymPPDef); }
#line 4531 "src/lexer.cc"
yy339:
	yych = *++cursor;
yy340:
	switch (yych) {
	case 0x00:
	case '\n':
	case '\r':	goto yy337;
	default:	goto yy339;
	}
yy341:
	++cursor;
	cursor -= 1;
#line 204 "src/lexer.re"
	{ PUSH_TOKEN(SymPPIf); }
#line 4546 "src/lexer.cc"
yy343:
	yych = *++cursor;
yy344:
	switch (yych) {
	case 0x00:
	case '\n':
	case '\r':	goto yy341;
	default:	goto yy343;
	}
yy345:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy354;
	default:	goto yy76;
	}
yy346:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy347;
	}
yy347:
#line 151 "src/lexer.re"
	{ PUSH_TOKEN(SymContinue); }
#line 4633 "src/lexer.cc"
yy348:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy349;
	}
yy349:
#line 165 "src/lexer.re"
	{ PUSH_TOKEN(SymRegister); }
#line 4705 "src/lexer.cc"
yy350:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy351;
	}
yy351:
#line 175 "src/lexer.re"
	{ PUSH_TOKEN(SymUnsigned); }
#line 4777 "src/lexer.cc"
yy352:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy353;
	}
yy353:
#line 177 "src/lexer.re"
	{ PUSH_TOKEN(SymVolatile); }
#line 4849 "src/lexer.cc"
yy354:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy75;
	default:	goto yy358;
	}
yy355:
	++cursor;
	cursor -= 1;
#line 209 "src/lexer.re"
	{ PUSH_TOKEN(SymPPDef); }
#line 4923 "src/lexer.cc"
yy357:
	yych = *++cursor;
yy358:
	switch (yych) {
	case 0x00:
	case '\n':
	case '\r':	goto yy355;
	default:	goto yy357;
	}
}
#line 214 "src/lexer.re"

    comment:
    
#line 4938 "src/lexer.cc"
{
	unsigned char yych;
	yych = *cursor;
	switch (yych) {
	case 0x00:	goto yy361;
	case '*':	goto yy365;
	default:	goto yy363;
	}
yy361:
	++cursor;
#line 219 "src/lexer.re"
	{ done = true; PUSH_TOKEN(SymComment); }
#line 4951 "src/lexer.cc"
yy363:
	++cursor;
yy364:
#line 218 "src/lexer.re"
	{ goto comment; }
#line 4957 "src/lexer.cc"
yy365:
	yych = *++cursor;
	switch (yych) {
	case '/':	goto yy366;
	default:	goto yy364;
	}
yy366:
	++cursor;
#line 217 "src/lexer.re"
	{ PUSH_TOKEN(SymComment); }
#line 4968 "src/lexer.cc"
}
#line 220 "src/lexer.re"

    pushtoken:
      token.str = Intern(last, cursor - last);
      result->add(token);
  }
  token.sym = SymEOF;
  token.str = S("");
  result->add(token);
  source->tokens = result;
  return !error;
}
