/* Generated by re2c */
#line 1 "src/lexer.re"
// vim:set ft=cpp:

#include "adlib/lib.h"
#include "adlib/set.h"
// "fixstr.h" must be included before "map.h"
#include "fixstr.h"
#include "adlib/map.h"

#include "lexer.h"

const char *SymbolNames[] = {
  "SymNone",
  "SymAuto",
  "SymBreak",
  "SymCase",
  "SymChar",
  "SymConst",
  "SymContinue",
  "SymDefault",
  "SymDo",
  "SymDouble",
  "SymElse",
  "SymEnum",
  "SymExtern",
  "SymFloat",
  "SymFor",
  "SymGoto",
  "SymIf",
  "SymInline",
  "SymInt",
  "SymLong",
  "SymRegister",
  "SymReturn",
  "SymShort",
  "SymSigned",
  "SymSizeof",
  "SymStatic",
  "SymStruct",
  "SymSwitch",
  "SymTypedef",
  "SymUnion",
  "SymUnsigned",
  "SymVoid",
  "SymVolatile",
  "SymWhile",
  "SymEXPORT_INLINE",
  "SymIdent",
  "SymLiteral",
  "SymOp",
  "SymSemicolon",
  "SymLPar",
  "SymRPar",
  "SymLBrkt",
  "SymRBrkt",
  "SymLBrace",
  "SymRBrace",
  "SymWS",
  "SymEOL",
  "SymComment",
  "SymBAD",
  "SymPPIf",
  "SymPPElse",
  "SymPPElif",
  "SymPPEndif",
  "SymPPDef",
  "SymPPOther",
  "SymEOF",
};

typedef Map<FixStr, Str *> InternMap;

Str *Intern(const char *ptr, Int len) {
  static InternMap *map = NULL;
  if (!map) {
    GCVar(map, new InternMap());
  }
  FixStr fs;
  fs.str = ptr;
  fs.len = len;
  Str *result = map->get(fs, NULL);
  if (!result) {
    result = new Str(ptr, len);
    // `ptr` above is an interior pointer whose contents may disappear
    // due to GC once the `SourceFile` object containing it is no
    // longer reachable.
    //
    // Therefore, we replace it with `result->c_str()`. This is not only
    // not an interior pointer, but is kept alive by the value that the
    // key is in use for.
    fs.str = result->c_str();
    map->add(fs, result);
  }
  return result;
}

#define PUSH_TOKEN(s) \
  token.sym = s; \
  goto pushtoken;

bool ReadSource(SourceFile *source) {
  if (!source->filedata) {
    source->filedata = ReadFile(source->filename);
  }
  return source->filedata != NULL;
}

bool Tokenize(SourceFile *source) {
  Str *input = source->filedata;
  const char *cursor = input->c_str();
  const char *marker = NULL;
  const char *ctxmarker = NULL;
  bool done = false;
  bool error = false;
  TokenList *result = new TokenList();
  Token token;
  while (!done) {
    const char *last = cursor;
    
#line 122 "src/lexer.cc"
{
	unsigned char yych;
	unsigned int yyaccept = 0;
	yych = *cursor;
	switch (yych) {
	case 0x00:	goto yy2;
	case '\t':
	case '\f':
	case ' ':	goto yy6;
	case '\n':	goto yy9;
	case '\r':	goto yy11;
	case '!':
	case '%':
	case '*':
	case '=':
	case '^':	goto yy12;
	case '"':	goto yy14;
	case '#':	goto yy15;
	case '&':	goto yy17;
	case '\'':	goto yy18;
	case '(':	goto yy19;
	case ')':	goto yy21;
	case '+':	goto yy23;
	case ',':
	case ':':
	case '?':
	case '~':	goto yy24;
	case '-':	goto yy25;
	case '.':	goto yy26;
	case '/':	goto yy27;
	case '0':	goto yy28;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy30;
	case ';':	goto yy32;
	case '<':	goto yy34;
	case '>':	goto yy35;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'h':
	case 'j':
	case 'k':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	case 'E':	goto yy39;
	case 'L':	goto yy40;
	case '[':	goto yy41;
	case '\\':	goto yy43;
	case ']':	goto yy44;
	case 'a':	goto yy46;
	case 'b':	goto yy47;
	case 'c':	goto yy48;
	case 'd':	goto yy49;
	case 'e':	goto yy50;
	case 'f':	goto yy51;
	case 'g':	goto yy52;
	case 'i':	goto yy53;
	case 'l':	goto yy54;
	case 'r':	goto yy55;
	case 's':	goto yy56;
	case 't':	goto yy57;
	case 'u':	goto yy58;
	case 'v':	goto yy59;
	case 'w':	goto yy60;
	case '{':	goto yy61;
	case '|':	goto yy63;
	case '}':	goto yy64;
	default:	goto yy4;
	}
yy2:
	++cursor;
#line 213 "src/lexer.re"
	{ done = true; continue; }
#line 231 "src/lexer.cc"
yy4:
	++cursor;
yy5:
#line 214 "src/lexer.re"
	{ error = true; PUSH_TOKEN(SymBAD); }
#line 237 "src/lexer.cc"
yy6:
	yych = *++cursor;
	switch (yych) {
	case '\t':
	case '\f':
	case ' ':	goto yy6;
	default:	goto yy8;
	}
yy8:
#line 203 "src/lexer.re"
	{ PUSH_TOKEN(SymWS); }
#line 249 "src/lexer.cc"
yy9:
	++cursor;
yy10:
#line 201 "src/lexer.re"
	{ PUSH_TOKEN(SymEOL); }
#line 255 "src/lexer.cc"
yy11:
	yych = *++cursor;
	switch (yych) {
	case '\n':	goto yy9;
	default:	goto yy10;
	}
yy12:
	yych = *++cursor;
	switch (yych) {
	case '=':	goto yy66;
	default:	goto yy13;
	}
yy13:
#line 196 "src/lexer.re"
	{ PUSH_TOKEN(SymOp); }
#line 271 "src/lexer.cc"
yy14:
	yyaccept = 0;
	yych = *(marker = ++cursor);
	switch (yych) {
	case 0x00:
	case '\n':
	case '\r':	goto yy5;
	default:	goto yy69;
	}
yy15:
	yych = *++cursor;
	switch (yych) {
	case 0x00:
	case '\n':
	case '\r':	goto yy74;
	case '\t':
	case '\f':
	case ' ':	goto yy15;
	case 'd':	goto yy78;
	case 'e':	goto yy79;
	case 'i':	goto yy80;
	case 'u':	goto yy81;
	default:	goto yy76;
	}
yy17:
	yych = *++cursor;
	switch (yych) {
	case '&':
	case '=':	goto yy66;
	default:	goto yy13;
	}
yy18:
	yyaccept = 0;
	yych = *(marker = ++cursor);
	switch (yych) {
	case 0x00:
	case '\n':
	case '\r':
	case '\'':	goto yy5;
	case '\\':	goto yy83;
	default:	goto yy82;
	}
yy19:
	++cursor;
#line 190 "src/lexer.re"
	{ PUSH_TOKEN(SymLPar); }
#line 318 "src/lexer.cc"
yy21:
	++cursor;
#line 191 "src/lexer.re"
	{ PUSH_TOKEN(SymRPar); }
#line 323 "src/lexer.cc"
yy23:
	yych = *++cursor;
	switch (yych) {
	case '+':
	case '=':	goto yy66;
	default:	goto yy13;
	}
yy24:
	++cursor;
	goto yy13;
yy25:
	yych = *++cursor;
	switch (yych) {
	case '-':
	case '=':
	case '>':	goto yy66;
	default:	goto yy13;
	}
yy26:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
	case '.':	goto yy84;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy85;
	default:	goto yy13;
	}
yy27:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
	case '*':	goto yy88;
	case '/':	goto yy90;
	case '=':	goto yy66;
	default:	goto yy13;
	}
yy28:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'E':
	case 'e':	goto yy94;
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy97;
	case 'X':
	case 'x':	goto yy99;
	default:	goto yy29;
	}
yy29:
#line 184 "src/lexer.re"
	{ PUSH_TOKEN(SymLiteral); }
#line 396 "src/lexer.cc"
yy30:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
	case '.':	goto yy91;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy30;
	case 'E':
	case 'e':	goto yy96;
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy97;
	default:	goto yy29;
	}
yy32:
	++cursor;
#line 198 "src/lexer.re"
	{ PUSH_TOKEN(SymSemicolon); }
#line 424 "src/lexer.cc"
yy34:
	yych = *++cursor;
	switch (yych) {
	case '<':	goto yy100;
	case '=':	goto yy66;
	default:	goto yy13;
	}
yy35:
	yych = *++cursor;
	switch (yych) {
	case '=':	goto yy66;
	case '>':	goto yy100;
	default:	goto yy13;
	}
yy36:
	yych = *++cursor;
yy37:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy38;
	}
yy38:
#line 181 "src/lexer.re"
	{ PUSH_TOKEN(SymIdent); }
#line 511 "src/lexer.cc"
yy39:
	yych = *++cursor;
	switch (yych) {
	case 'X':	goto yy101;
	default:	goto yy37;
	}
yy40:
	yyaccept = 3;
	yych = *(marker = ++cursor);
	switch (yych) {
	case '"':	goto yy68;
	case '\'':	goto yy102;
	default:	goto yy37;
	}
yy41:
	++cursor;
#line 192 "src/lexer.re"
	{ PUSH_TOKEN(SymLBrkt); }
#line 530 "src/lexer.cc"
yy43:
	yyaccept = 0;
	yych = *(marker = ++cursor);
	switch (yych) {
	case '\t':
	case '\n':
	case '\f':
	case '\r':
	case ' ':	goto yy104;
	default:	goto yy5;
	}
yy44:
	++cursor;
#line 193 "src/lexer.re"
	{ PUSH_TOKEN(SymRBrkt); }
#line 546 "src/lexer.cc"
yy46:
	yych = *++cursor;
	switch (yych) {
	case 'u':	goto yy108;
	default:	goto yy37;
	}
yy47:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy109;
	default:	goto yy37;
	}
yy48:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy110;
	case 'h':	goto yy111;
	case 'o':	goto yy112;
	default:	goto yy37;
	}
yy49:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy113;
	case 'o':	goto yy114;
	default:	goto yy37;
	}
yy50:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy116;
	case 'n':	goto yy117;
	case 'x':	goto yy118;
	default:	goto yy37;
	}
yy51:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy119;
	case 'o':	goto yy120;
	default:	goto yy37;
	}
yy52:
	yych = *++cursor;
	switch (yych) {
	case 'o':	goto yy121;
	default:	goto yy37;
	}
yy53:
	yych = *++cursor;
	switch (yych) {
	case 'f':	goto yy122;
	case 'n':	goto yy124;
	default:	goto yy37;
	}
yy54:
	yych = *++cursor;
	switch (yych) {
	case 'o':	goto yy125;
	default:	goto yy37;
	}
yy55:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy126;
	default:	goto yy37;
	}
yy56:
	yych = *++cursor;
	switch (yych) {
	case 'h':	goto yy127;
	case 'i':	goto yy128;
	case 't':	goto yy129;
	case 'w':	goto yy130;
	default:	goto yy37;
	}
yy57:
	yych = *++cursor;
	switch (yych) {
	case 'y':	goto yy131;
	default:	goto yy37;
	}
yy58:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy132;
	default:	goto yy37;
	}
yy59:
	yych = *++cursor;
	switch (yych) {
	case 'o':	goto yy133;
	default:	goto yy37;
	}
yy60:
	yych = *++cursor;
	switch (yych) {
	case 'h':	goto yy134;
	default:	goto yy37;
	}
yy61:
	++cursor;
#line 194 "src/lexer.re"
	{ PUSH_TOKEN(SymLBrace); }
#line 651 "src/lexer.cc"
yy63:
	yych = *++cursor;
	switch (yych) {
	case '=':
	case '|':	goto yy66;
	default:	goto yy13;
	}
yy64:
	++cursor;
#line 195 "src/lexer.re"
	{ PUSH_TOKEN(SymRBrace); }
#line 663 "src/lexer.cc"
yy66:
	++cursor;
yy67:
#line 197 "src/lexer.re"
	{ PUSH_TOKEN(SymOp); }
#line 669 "src/lexer.cc"
yy68:
	yych = *++cursor;
yy69:
	switch (yych) {
	case 0x00:
	case '\n':
	case '\r':	goto yy70;
	case '"':	goto yy71;
	case '\\':	goto yy73;
	default:	goto yy68;
	}
yy70:
	cursor = marker;
	switch (yyaccept) {
	case 0: 	goto yy5;
	case 1: 	goto yy13;
	case 2: 	goto yy29;
	case 3: 	goto yy38;
	case 4: 	goto yy87;
	case 5: 	goto yy92;
	default:	goto yy95;
	}
yy71:
	++cursor;
#line 186 "src/lexer.re"
	{ PUSH_TOKEN(SymLiteral); }
#line 696 "src/lexer.cc"
yy73:
	yych = *++cursor;
	switch (yych) {
	case 0x00:
	case '\n':
	case '\r':	goto yy70;
	default:	goto yy68;
	}
yy74:
	++cursor;
	cursor -= 1;
#line 212 "src/lexer.re"
	{ PUSH_TOKEN(SymPPOther); }
#line 710 "src/lexer.cc"
yy76:
	yych = *++cursor;
yy77:
	switch (yych) {
	case 0x00:
	case '\n':
	case '\r':	goto yy74;
	default:	goto yy76;
	}
yy78:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy135;
	default:	goto yy77;
	}
yy79:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy136;
	case 'n':	goto yy137;
	default:	goto yy77;
	}
yy80:
	yych = *++cursor;
	switch (yych) {
	case 'f':	goto yy138;
	default:	goto yy77;
	}
yy81:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy139;
	default:	goto yy77;
	}
yy82:
	yych = *++cursor;
	switch (yych) {
	case '\'':	goto yy140;
	default:	goto yy70;
	}
yy83:
	yych = *++cursor;
	switch (yych) {
	case '\'':
	case '\\':	goto yy142;
	default:	goto yy143;
	}
yy84:
	yych = *++cursor;
	switch (yych) {
	case '.':	goto yy66;
	default:	goto yy70;
	}
yy85:
	yyaccept = 4;
	yych = *(marker = ++cursor);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy85;
	case 'E':
	case 'e':	goto yy144;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy145;
	default:	goto yy87;
	}
yy87:
#line 188 "src/lexer.re"
	{ PUSH_TOKEN(SymLiteral); }
#line 789 "src/lexer.cc"
yy88:
	++cursor;
#line 200 "src/lexer.re"
	{ goto comment; }
#line 794 "src/lexer.cc"
yy90:
	yych = *++cursor;
	switch (yych) {
	case 0x00:
	case '\n':
	case '\r':	goto yy70;
	default:	goto yy146;
	}
yy91:
	yyaccept = 5;
	yych = *(marker = ++cursor);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy85;
	case 'E':
	case 'e':	goto yy149;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy150;
	default:	goto yy92;
	}
yy92:
#line 189 "src/lexer.re"
	{ PUSH_TOKEN(SymLiteral); }
#line 828 "src/lexer.cc"
yy93:
	yyaccept = 6;
	yych = *(marker = ++cursor);
yy94:
	switch (yych) {
	case '.':	goto yy91;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy93;
	case '8':
	case '9':	goto yy30;
	case 'E':
	case 'e':	goto yy96;
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy151;
	default:	goto yy95;
	}
yy95:
#line 183 "src/lexer.re"
	{ PUSH_TOKEN(SymLiteral); }
#line 856 "src/lexer.cc"
yy96:
	yych = *++cursor;
	switch (yych) {
	case '+':
	case '-':	goto yy153;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy154;
	default:	goto yy70;
	}
yy97:
	yych = *++cursor;
	switch (yych) {
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy97;
	default:	goto yy29;
	}
yy99:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy157;
	default:	goto yy70;
	}
yy100:
	yych = *++cursor;
	switch (yych) {
	case '=':	goto yy66;
	default:	goto yy67;
	}
yy101:
	yych = *++cursor;
	switch (yych) {
	case 'P':	goto yy160;
	default:	goto yy37;
	}
yy102:
	yych = *++cursor;
	switch (yych) {
	case 0x00:
	case '\n':
	case '\r':
	case '\'':	goto yy70;
	case '\\':	goto yy83;
	default:	goto yy82;
	}
yy103:
	yych = *++cursor;
yy104:
	switch (yych) {
	case '\t':
	case '\f':
	case ' ':	goto yy103;
	case '\n':
		ctxmarker = cursor;
		goto yy105;
	case '\r':
		ctxmarker = cursor;
		goto yy107;
	default:	goto yy70;
	}
yy105:
	++cursor;
yy106:
	cursor = ctxmarker;
#line 202 "src/lexer.re"
	{ PUSH_TOKEN(SymWS); }
#line 953 "src/lexer.cc"
yy107:
	yych = *++cursor;
	switch (yych) {
	case '\n':	goto yy105;
	default:	goto yy106;
	}
yy108:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy161;
	default:	goto yy37;
	}
yy109:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy162;
	default:	goto yy37;
	}
yy110:
	yych = *++cursor;
	switch (yych) {
	case 's':	goto yy163;
	default:	goto yy37;
	}
yy111:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy164;
	default:	goto yy37;
	}
yy112:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy165;
	default:	goto yy37;
	}
yy113:
	yych = *++cursor;
	switch (yych) {
	case 'f':	goto yy166;
	default:	goto yy37;
	}
yy114:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	case 'u':	goto yy167;
	default:	goto yy115;
	}
yy115:
#line 154 "src/lexer.re"
	{ PUSH_TOKEN(SymDo); }
#line 1067 "src/lexer.cc"
yy116:
	yych = *++cursor;
	switch (yych) {
	case 's':	goto yy168;
	default:	goto yy37;
	}
yy117:
	yych = *++cursor;
	switch (yych) {
	case 'u':	goto yy169;
	default:	goto yy37;
	}
yy118:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy170;
	default:	goto yy37;
	}
yy119:
	yych = *++cursor;
	switch (yych) {
	case 'o':	goto yy171;
	default:	goto yy37;
	}
yy120:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy172;
	default:	goto yy37;
	}
yy121:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy174;
	default:	goto yy37;
	}
yy122:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy123;
	}
yy123:
#line 162 "src/lexer.re"
	{ PUSH_TOKEN(SymIf); }
#line 1175 "src/lexer.cc"
yy124:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy175;
	case 't':	goto yy176;
	default:	goto yy37;
	}
yy125:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy178;
	default:	goto yy37;
	}
yy126:
	yych = *++cursor;
	switch (yych) {
	case 'g':	goto yy179;
	case 't':	goto yy180;
	default:	goto yy37;
	}
yy127:
	yych = *++cursor;
	switch (yych) {
	case 'o':	goto yy181;
	default:	goto yy37;
	}
yy128:
	yych = *++cursor;
	switch (yych) {
	case 'g':	goto yy182;
	case 'z':	goto yy183;
	default:	goto yy37;
	}
yy129:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy184;
	case 'r':	goto yy185;
	default:	goto yy37;
	}
yy130:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy186;
	default:	goto yy37;
	}
yy131:
	yych = *++cursor;
	switch (yych) {
	case 'p':	goto yy187;
	default:	goto yy37;
	}
yy132:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy188;
	case 's':	goto yy189;
	default:	goto yy37;
	}
yy133:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy190;
	case 'l':	goto yy191;
	default:	goto yy37;
	}
yy134:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy192;
	default:	goto yy37;
	}
yy135:
	yych = *++cursor;
	switch (yych) {
	case 'f':	goto yy193;
	default:	goto yy77;
	}
yy136:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy194;
	case 's':	goto yy195;
	default:	goto yy77;
	}
yy137:
	yych = *++cursor;
	switch (yych) {
	case 'd':	goto yy196;
	default:	goto yy77;
	}
yy138:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy76;
	case 'd':	goto yy201;
	case 'n':	goto yy202;
	default:	goto yy200;
	}
yy139:
	yych = *++cursor;
	switch (yych) {
	case 'd':	goto yy203;
	default:	goto yy77;
	}
yy140:
	++cursor;
#line 185 "src/lexer.re"
	{ PUSH_TOKEN(SymLiteral); }
#line 1345 "src/lexer.cc"
yy142:
	yych = *++cursor;
yy143:
	switch (yych) {
	case 0x00:
	case '\n':
	case '\r':
	case '\\':	goto yy70;
	case '\'':	goto yy140;
	default:	goto yy142;
	}
yy144:
	yych = *++cursor;
	switch (yych) {
	case '+':
	case '-':	goto yy204;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy205;
	default:	goto yy70;
	}
yy145:
	++cursor;
	goto yy87;
yy146:
	yych = *++cursor;
	switch (yych) {
	case 0x00:
	case '\n':
	case '\r':	goto yy148;
	default:	goto yy146;
	}
yy148:
#line 199 "src/lexer.re"
	{ PUSH_TOKEN(SymComment); }
#line 1388 "src/lexer.cc"
yy149:
	yych = *++cursor;
	switch (yych) {
	case '+':
	case '-':	goto yy207;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy208;
	default:	goto yy70;
	}
yy150:
	++cursor;
	goto yy92;
yy151:
	yych = *++cursor;
	switch (yych) {
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy151;
	default:	goto yy95;
	}
yy153:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy154;
	default:	goto yy70;
	}
yy154:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy154;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy210;
	default:	goto yy156;
	}
yy156:
#line 187 "src/lexer.re"
	{ PUSH_TOKEN(SymLiteral); }
#line 1455 "src/lexer.cc"
yy157:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy157;
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy211;
	default:	goto yy159;
	}
yy159:
#line 182 "src/lexer.re"
	{ PUSH_TOKEN(SymLiteral); }
#line 1490 "src/lexer.cc"
yy160:
	yych = *++cursor;
	switch (yych) {
	case 'O':	goto yy213;
	default:	goto yy37;
	}
yy161:
	yych = *++cursor;
	switch (yych) {
	case 'o':	goto yy214;
	default:	goto yy37;
	}
yy162:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy216;
	default:	goto yy37;
	}
yy163:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy217;
	default:	goto yy37;
	}
yy164:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy219;
	default:	goto yy37;
	}
yy165:
	yych = *++cursor;
	switch (yych) {
	case 's':	goto yy221;
	case 't':	goto yy222;
	default:	goto yy37;
	}
yy166:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy223;
	default:	goto yy37;
	}
yy167:
	yych = *++cursor;
	switch (yych) {
	case 'b':	goto yy224;
	default:	goto yy37;
	}
yy168:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy225;
	default:	goto yy37;
	}
yy169:
	yych = *++cursor;
	switch (yych) {
	case 'm':	goto yy227;
	default:	goto yy37;
	}
yy170:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy229;
	default:	goto yy37;
	}
yy171:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy230;
	default:	goto yy37;
	}
yy172:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy173;
	}
yy173:
#line 160 "src/lexer.re"
	{ PUSH_TOKEN(SymFor); }
#line 1635 "src/lexer.cc"
yy174:
	yych = *++cursor;
	switch (yych) {
	case 'o':	goto yy231;
	default:	goto yy37;
	}
yy175:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy233;
	default:	goto yy37;
	}
yy176:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy177;
	}
yy177:
#line 164 "src/lexer.re"
	{ PUSH_TOKEN(SymInt); }
#line 1719 "src/lexer.cc"
yy178:
	yych = *++cursor;
	switch (yych) {
	case 'g':	goto yy234;
	default:	goto yy37;
	}
yy179:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy236;
	default:	goto yy37;
	}
yy180:
	yych = *++cursor;
	switch (yych) {
	case 'u':	goto yy237;
	default:	goto yy37;
	}
yy181:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy238;
	default:	goto yy37;
	}
yy182:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy239;
	default:	goto yy37;
	}
yy183:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy240;
	default:	goto yy37;
	}
yy184:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy241;
	default:	goto yy37;
	}
yy185:
	yych = *++cursor;
	switch (yych) {
	case 'u':	goto yy242;
	default:	goto yy37;
	}
yy186:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy243;
	default:	goto yy37;
	}
yy187:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy244;
	default:	goto yy37;
	}
yy188:
	yych = *++cursor;
	switch (yych) {
	case 'o':	goto yy245;
	default:	goto yy37;
	}
yy189:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy246;
	default:	goto yy37;
	}
yy190:
	yych = *++cursor;
	switch (yych) {
	case 'd':	goto yy247;
	default:	goto yy37;
	}
yy191:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy249;
	default:	goto yy37;
	}
yy192:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy250;
	default:	goto yy37;
	}
yy193:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy251;
	default:	goto yy77;
	}
yy194:
	yych = *++cursor;
	switch (yych) {
	case 'f':	goto yy252;
	default:	goto yy77;
	}
yy195:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy253;
	default:	goto yy77;
	}
yy196:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy254;
	default:	goto yy77;
	}
yy197:
	++cursor;
	cursor -= 1;
#line 204 "src/lexer.re"
	{ PUSH_TOKEN(SymPPIf); }
#line 1839 "src/lexer.cc"
yy199:
	yych = *++cursor;
yy200:
	switch (yych) {
	case 0x00:
	case '\n':
	case '\r':	goto yy197;
	default:	goto yy199;
	}
yy201:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy255;
	default:	goto yy77;
	}
yy202:
	yych = *++cursor;
	switch (yych) {
	case 'd':	goto yy256;
	default:	goto yy77;
	}
yy203:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy257;
	default:	goto yy77;
	}
yy204:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy205;
	default:	goto yy70;
	}
yy205:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy205;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy145;
	default:	goto yy87;
	}
yy207:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy208;
	default:	goto yy70;
	}
yy208:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy208;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy150;
	default:	goto yy92;
	}
yy210:
	++cursor;
	goto yy156;
yy211:
	yych = *++cursor;
	switch (yych) {
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy211;
	default:	goto yy159;
	}
yy213:
	yych = *++cursor;
	switch (yych) {
	case 'R':	goto yy258;
	default:	goto yy37;
	}
yy214:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy215;
	}
yy215:
#line 147 "src/lexer.re"
	{ PUSH_TOKEN(SymAuto); }
#line 2024 "src/lexer.cc"
yy216:
	yych = *++cursor;
	switch (yych) {
	case 'k':	goto yy259;
	default:	goto yy37;
	}
yy217:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy218;
	}
yy218:
#line 149 "src/lexer.re"
	{ PUSH_TOKEN(SymCase); }
#line 2102 "src/lexer.cc"
yy219:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy220;
	}
yy220:
#line 150 "src/lexer.re"
	{ PUSH_TOKEN(SymChar); }
#line 2174 "src/lexer.cc"
yy221:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy261;
	default:	goto yy37;
	}
yy222:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy263;
	default:	goto yy37;
	}
yy223:
	yych = *++cursor;
	switch (yych) {
	case 'u':	goto yy264;
	default:	goto yy37;
	}
yy224:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy265;
	default:	goto yy37;
	}
yy225:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy226;
	}
yy226:
#line 156 "src/lexer.re"
	{ PUSH_TOKEN(SymElse); }
#line 2270 "src/lexer.cc"
yy227:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy228;
	}
yy228:
#line 157 "src/lexer.re"
	{ PUSH_TOKEN(SymEnum); }
#line 2342 "src/lexer.cc"
yy229:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy266;
	default:	goto yy37;
	}
yy230:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy267;
	default:	goto yy37;
	}
yy231:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy232;
	}
yy232:
#line 161 "src/lexer.re"
	{ PUSH_TOKEN(SymGoto); }
#line 2426 "src/lexer.cc"
yy233:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy269;
	default:	goto yy37;
	}
yy234:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy235;
	}
yy235:
#line 165 "src/lexer.re"
	{ PUSH_TOKEN(SymLong); }
#line 2504 "src/lexer.cc"
yy236:
	yych = *++cursor;
	switch (yych) {
	case 's':	goto yy270;
	default:	goto yy37;
	}
yy237:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy271;
	default:	goto yy37;
	}
yy238:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy272;
	default:	goto yy37;
	}
yy239:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy274;
	default:	goto yy37;
	}
yy240:
	yych = *++cursor;
	switch (yych) {
	case 'o':	goto yy275;
	default:	goto yy37;
	}
yy241:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy276;
	default:	goto yy37;
	}
yy242:
	yych = *++cursor;
	switch (yych) {
	case 'c':	goto yy277;
	default:	goto yy37;
	}
yy243:
	yych = *++cursor;
	switch (yych) {
	case 'c':	goto yy278;
	default:	goto yy37;
	}
yy244:
	yych = *++cursor;
	switch (yych) {
	case 'd':	goto yy279;
	default:	goto yy37;
	}
yy245:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy280;
	default:	goto yy37;
	}
yy246:
	yych = *++cursor;
	switch (yych) {
	case 'g':	goto yy282;
	default:	goto yy37;
	}
yy247:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy248;
	}
yy248:
#line 177 "src/lexer.re"
	{ PUSH_TOKEN(SymVoid); }
#line 2642 "src/lexer.cc"
yy249:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy283;
	default:	goto yy37;
	}
yy250:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy284;
	default:	goto yy37;
	}
yy251:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy286;
	default:	goto yy77;
	}
yy252:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy76;
	default:	goto yy290;
	}
yy253:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy76;
	default:	goto yy294;
	}
yy254:
	yych = *++cursor;
	switch (yych) {
	case 'f':	goto yy295;
	default:	goto yy77;
	}
yy255:
	yych = *++cursor;
	switch (yych) {
	case 'f':	goto yy296;
	default:	goto yy77;
	}
yy256:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy297;
	default:	goto yy77;
	}
yy257:
	yych = *++cursor;
	switch (yych) {
	case 'f':	goto yy298;
	default:	goto yy77;
	}
yy258:
	yych = *++cursor;
	switch (yych) {
	case 'T':	goto yy299;
	default:	goto yy37;
	}
yy259:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy260;
	}
yy260:
#line 148 "src/lexer.re"
	{ PUSH_TOKEN(SymBreak); }
#line 2898 "src/lexer.cc"
yy261:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy262;
	}
yy262:
#line 151 "src/lexer.re"
	{ PUSH_TOKEN(SymConst); }
#line 2970 "src/lexer.cc"
yy263:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy300;
	default:	goto yy37;
	}
yy264:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy301;
	default:	goto yy37;
	}
yy265:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy302;
	default:	goto yy37;
	}
yy266:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy304;
	default:	goto yy37;
	}
yy267:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy268;
	}
yy268:
#line 159 "src/lexer.re"
	{ PUSH_TOKEN(SymFloat); }
#line 3066 "src/lexer.cc"
yy269:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy306;
	default:	goto yy37;
	}
yy270:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy308;
	default:	goto yy37;
	}
yy271:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy309;
	default:	goto yy37;
	}
yy272:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy273;
	}
yy273:
#line 168 "src/lexer.re"
	{ PUSH_TOKEN(SymShort); }
#line 3156 "src/lexer.cc"
yy274:
	yych = *++cursor;
	switch (yych) {
	case 'd':	goto yy311;
	default:	goto yy37;
	}
yy275:
	yych = *++cursor;
	switch (yych) {
	case 'f':	goto yy313;
	default:	goto yy37;
	}
yy276:
	yych = *++cursor;
	switch (yych) {
	case 'c':	goto yy315;
	default:	goto yy37;
	}
yy277:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy317;
	default:	goto yy37;
	}
yy278:
	yych = *++cursor;
	switch (yych) {
	case 'h':	goto yy319;
	default:	goto yy37;
	}
yy279:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy321;
	default:	goto yy37;
	}
yy280:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy281;
	}
yy281:
#line 175 "src/lexer.re"
	{ PUSH_TOKEN(SymUnion); }
#line 3264 "src/lexer.cc"
yy282:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy322;
	default:	goto yy37;
	}
yy283:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy323;
	default:	goto yy37;
	}
yy284:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy285;
	}
yy285:
#line 179 "src/lexer.re"
	{ PUSH_TOKEN(SymWhile); }
#line 3348 "src/lexer.cc"
yy286:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy324;
	default:	goto yy77;
	}
yy287:
	++cursor;
	cursor -= 1;
#line 208 "src/lexer.re"
	{ PUSH_TOKEN(SymPPElif); }
#line 3360 "src/lexer.cc"
yy289:
	yych = *++cursor;
yy290:
	switch (yych) {
	case 0x00:
	case '\n':
	case '\r':	goto yy287;
	default:	goto yy289;
	}
yy291:
	++cursor;
	cursor -= 1;
#line 207 "src/lexer.re"
	{ PUSH_TOKEN(SymPPElse); }
#line 3375 "src/lexer.cc"
yy293:
	yych = *++cursor;
yy294:
	switch (yych) {
	case 0x00:
	case '\n':
	case '\r':	goto yy291;
	default:	goto yy293;
	}
yy295:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy76;
	default:	goto yy328;
	}
yy296:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy76;
	default:	goto yy332;
	}
yy297:
	yych = *++cursor;
	switch (yych) {
	case 'f':	goto yy333;
	default:	goto yy77;
	}
yy298:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy334;
	default:	goto yy77;
	}
yy299:
	yych = *++cursor;
	switch (yych) {
	case '_':	goto yy335;
	default:	goto yy37;
	}
yy300:
	yych = *++cursor;
	switch (yych) {
	case 'u':	goto yy336;
	default:	goto yy37;
	}
yy301:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy337;
	default:	goto yy37;
	}
yy302:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy303;
	}
yy303:
#line 155 "src/lexer.re"
	{ PUSH_TOKEN(SymDouble); }
#line 3622 "src/lexer.cc"
yy304:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy305;
	}
yy305:
#line 158 "src/lexer.re"
	{ PUSH_TOKEN(SymExtern); }
#line 3694 "src/lexer.cc"
yy306:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy307;
	}
yy307:
#line 163 "src/lexer.re"
	{ PUSH_TOKEN(SymInline); }
#line 3766 "src/lexer.cc"
yy308:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy339;
	default:	goto yy37;
	}
yy309:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy310;
	}
yy310:
#line 167 "src/lexer.re"
	{ PUSH_TOKEN(SymReturn); }
#line 3844 "src/lexer.cc"
yy311:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy312;
	}
yy312:
#line 169 "src/lexer.re"
	{ PUSH_TOKEN(SymSigned); }
#line 3916 "src/lexer.cc"
yy313:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy314;
	}
yy314:
#line 170 "src/lexer.re"
	{ PUSH_TOKEN(SymSizeof); }
#line 3988 "src/lexer.cc"
yy315:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy316;
	}
yy316:
#line 171 "src/lexer.re"
	{ PUSH_TOKEN(SymStatic); }
#line 4060 "src/lexer.cc"
yy317:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy318;
	}
yy318:
#line 172 "src/lexer.re"
	{ PUSH_TOKEN(SymStruct); }
#line 4132 "src/lexer.cc"
yy319:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy320;
	}
yy320:
#line 173 "src/lexer.re"
	{ PUSH_TOKEN(SymSwitch); }
#line 4204 "src/lexer.cc"
yy321:
	yych = *++cursor;
	switch (yych) {
	case 'f':	goto yy340;
	default:	goto yy37;
	}
yy322:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy342;
	default:	goto yy37;
	}
yy323:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy343;
	default:	goto yy37;
	}
yy324:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy76;
	default:	goto yy347;
	}
yy325:
	++cursor;
	cursor -= 1;
#line 209 "src/lexer.re"
	{ PUSH_TOKEN(SymPPEndif); }
#line 4296 "src/lexer.cc"
yy327:
	yych = *++cursor;
yy328:
	switch (yych) {
	case 0x00:
	case '\n':
	case '\r':	goto yy325;
	default:	goto yy327;
	}
yy329:
	++cursor;
	cursor -= 1;
#line 205 "src/lexer.re"
	{ PUSH_TOKEN(SymPPIf); }
#line 4311 "src/lexer.cc"
yy331:
	yych = *++cursor;
yy332:
	switch (yych) {
	case 0x00:
	case '\n':
	case '\r':	goto yy329;
	default:	goto yy331;
	}
yy333:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy76;
	default:	goto yy351;
	}
yy334:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy352;
	default:	goto yy77;
	}
yy335:
	yych = *++cursor;
	switch (yych) {
	case 'I':	goto yy353;
	default:	goto yy37;
	}
yy336:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy354;
	default:	goto yy37;
	}
yy337:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy338;
	}
yy338:
#line 153 "src/lexer.re"
	{ PUSH_TOKEN(SymDefault); }
#line 4478 "src/lexer.cc"
yy339:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy356;
	default:	goto yy37;
	}
yy340:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy341;
	}
yy341:
#line 174 "src/lexer.re"
	{ PUSH_TOKEN(SymTypedef); }
#line 4556 "src/lexer.cc"
yy342:
	yych = *++cursor;
	switch (yych) {
	case 'd':	goto yy358;
	default:	goto yy37;
	}
yy343:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy360;
	default:	goto yy37;
	}
yy344:
	++cursor;
	cursor -= 1;
#line 210 "src/lexer.re"
	{ PUSH_TOKEN(SymPPDef); }
#line 4574 "src/lexer.cc"
yy346:
	yych = *++cursor;
yy347:
	switch (yych) {
	case 0x00:
	case '\n':
	case '\r':	goto yy344;
	default:	goto yy346;
	}
yy348:
	++cursor;
	cursor -= 1;
#line 206 "src/lexer.re"
	{ PUSH_TOKEN(SymPPIf); }
#line 4589 "src/lexer.cc"
yy350:
	yych = *++cursor;
yy351:
	switch (yych) {
	case 0x00:
	case '\n':
	case '\r':	goto yy348;
	default:	goto yy350;
	}
yy352:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy362;
	default:	goto yy77;
	}
yy353:
	yych = *++cursor;
	switch (yych) {
	case 'N':	goto yy363;
	default:	goto yy37;
	}
yy354:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy355;
	}
yy355:
#line 152 "src/lexer.re"
	{ PUSH_TOKEN(SymContinue); }
#line 4682 "src/lexer.cc"
yy356:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy357;
	}
yy357:
#line 166 "src/lexer.re"
	{ PUSH_TOKEN(SymRegister); }
#line 4754 "src/lexer.cc"
yy358:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy359;
	}
yy359:
#line 176 "src/lexer.re"
	{ PUSH_TOKEN(SymUnsigned); }
#line 4826 "src/lexer.cc"
yy360:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy361;
	}
yy361:
#line 178 "src/lexer.re"
	{ PUSH_TOKEN(SymVolatile); }
#line 4898 "src/lexer.cc"
yy362:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy76;
	default:	goto yy367;
	}
yy363:
	yych = *++cursor;
	switch (yych) {
	case 'L':	goto yy368;
	default:	goto yy37;
	}
yy364:
	++cursor;
	cursor -= 1;
#line 211 "src/lexer.re"
	{ PUSH_TOKEN(SymPPDef); }
#line 4978 "src/lexer.cc"
yy366:
	yych = *++cursor;
yy367:
	switch (yych) {
	case 0x00:
	case '\n':
	case '\r':	goto yy364;
	default:	goto yy366;
	}
yy368:
	yych = *++cursor;
	switch (yych) {
	case 'I':	goto yy369;
	default:	goto yy37;
	}
yy369:
	yych = *++cursor;
	switch (yych) {
	case 'N':	goto yy370;
	default:	goto yy37;
	}
yy370:
	yych = *++cursor;
	switch (yych) {
	case 'E':	goto yy371;
	default:	goto yy37;
	}
yy371:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy36;
	default:	goto yy372;
	}
yy372:
#line 180 "src/lexer.re"
	{ PUSH_TOKEN(SymEXPORT_INLINE); }
#line 5077 "src/lexer.cc"
}
#line 216 "src/lexer.re"

    comment:
    
#line 5083 "src/lexer.cc"
{
	unsigned char yych;
	yych = *cursor;
	switch (yych) {
	case 0x00:	goto yy375;
	case '*':	goto yy379;
	default:	goto yy377;
	}
yy375:
	++cursor;
#line 221 "src/lexer.re"
	{ done = true; PUSH_TOKEN(SymComment); }
#line 5096 "src/lexer.cc"
yy377:
	++cursor;
yy378:
#line 220 "src/lexer.re"
	{ goto comment; }
#line 5102 "src/lexer.cc"
yy379:
	yych = *++cursor;
	switch (yych) {
	case '/':	goto yy380;
	default:	goto yy378;
	}
yy380:
	++cursor;
#line 219 "src/lexer.re"
	{ PUSH_TOKEN(SymComment); }
#line 5113 "src/lexer.cc"
}
#line 222 "src/lexer.re"

    pushtoken:
      token.str = Intern(last, cursor - last);
      result->add(token);
  }
  token.sym = SymEOF;
  token.str = S("");
  result->add(token);
  source->tokens = result;
  return !error;
}
